spring:
  application:
    name: mall-monitor
  security: #Configure login username and password
    user:
      name: macro
      password: 123456
  boot:  #Do not display monitoring information for admin-server
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8101
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
