spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: reader
    password: 123456
logging:
  path: /var/logs #Configure the log generation path