spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
logging:
  level:
    root: info #Log configuration DEBUG, INFO, WARN, ERROR
    com.macro.mall: debug
    com.macro.mall.demo.service.FeignAdminService: debug