server:
  port: 8180
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #Connection pool initialization size
      min-idle: 10 #Minimum number of idle connections
      max-active: 20 #Maximum number of connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Do not count these request data
      stat-view-servlet: #Login username and password for accessing monitoring web pages
        login-username: druid
        login-password: druid
  rabbitmq: #rabbitmq related configuration
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      enabled: true #Open File Upload
      max-file-size: 10MB #Limit file upload size to 10M
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #Enable monitoring of SpringBoot Admin
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jwt:
  tokenHeader: Authorization #JWT stored request header
  secret: mall-admin-secret #JWT encryption and decryption key
  expiration: 604800 #JWT overdue time (60 * 60 * 24)
  tokenHead: Bearer  #Get the beginning in JWT load
secure:
  ignored:
    urls: #Safe Path Whitelist
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /minio/upload
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # access domain for oss external services
    accessKeyId: test # User ID used in access authentication
    accessKeySecret: test # Key used by the user to encrypt the signature string and OSS to verify the signature string
    bucketName: macro-oss # storage space for oss
    policy:
      expire: 300 # Signature validity(S)
    maxSize: 10 # Upload File size (M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # Callback address after File Upload succeeded
    dir:
      prefix: mall/images/ # Upload folder path prefix
minio:
  endpoint: http://192.168.6.132:9090 #Address of the MinIO service
  bucketName: mall #Bucket name
  accessKey: minioadmin #Access key
  secretKey: minioadmin #Secret key