aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # access domain for oss external services
    accessKeyId: test # User ID used in access authentication
    accessKeySecret: test # Key used by the user to encrypt the signature string and OSS to verify the signature string
    bucketName: macro-oss # storage space for oss
    policy:
      expire: 300 # Signature validity(S)
    maxSize: 10 # Upload File size (M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # Callback address after File Upload succeeded
    dir:
      prefix: mall/images/ # Upload folder path prefix
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
logging:
  level:
    root: info #Log configuration DEBUG, INFO, WARN, ERROR
    com.macro.mall: debug