spring:
  datasource:
    url: jdbc:mysql://1.14.193.151:3307/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234zhaoJIA+
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost