server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
    druid:
      initial-size: 5 #Connection pool initialization size
      min-idle: 10 #Minimum idle connections
      max-active: 20 #Maximum number of connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Do not count these request data
      stat-view-servlet: #Login username and password for accessing the monitoring webpage
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  redis:
    host: localhost # Redis server address
    database: 0 # Redis database index (default is 0)
    port: 6379 # Redis server connection port
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # Maximum number of connections in the connection pool (use a negative value to indicate no limit)
        max-wait: -1ms # Connection pool maximum blocking wait time (use a negative value to indicate no limit)
        max-idle: 8 # Maximum idle connections in the connection pool
        min-idle: 0 # The smallest idle connection in the connection pool
    timeout: 3000ms # Connection timeout (ms)
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #Must be set to true if callbacks are required for asynchronous messages
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #Enable monitoring of SpringBoot Admin
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jwt:
  tokenHeader: Authorization #JWT stored request header
  secret: mall-portal-secret #JWT encryption and decryption key
  expiration: 604800 #JWT overdue time (60 * 60 * 24)
  tokenHead: Bearer #Get the beginning in JWT load
secure:
  ignored:
    urls: #Safe path whitelist
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
# Custom redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 90 # Verification code expiration time
# Custom message queue name
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
