server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
    druid:
      initial-size: 5 #Connection pool initialization size
      min-idle: 10 #Minimum number of idle connections
      max-active: 20 #Maximum number of connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Do not count these request data
      stat-view-servlet: #Login username and password for accessing monitoring web pages
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #Enable monitoring of SpringBoot Admin
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



