server:
  port: 8301
spring:
  application:
    name: mall-config
  profiles:
    active: native #Use local configuration, you can use git storage instead of git
  cloud:
    config:
      server:
        native: #Local Warehouse Stock Storage
          search-locations: classpath:/config/{application}
        git: #Git repository storage
          uri: https://gitee.com/macrozheng/mall-config.git
          username: macro
          password: 123456
          clone-on-start: true
          search-paths: '{application}'
