spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: reader
    password: 123456
  data:
    elasticsearch:
      cluster-nodes: es:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: http://es:9200
logging:
  path: /var/logs #Configure the log generation path
management:
  health:
    elasticsearch:
      response-timeout: 1000ms #Increase health check-up Timeout