spring:
  datasource:
    url: jdbc:mysql://47.93.5.25:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    elasticsearch:
      cluster-nodes: 47.93.5.25:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: http://47.93.5.25:9200
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug