spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info #Log configuration DEBUG, INFO, WARN, ERROR
    com.macro.mall: debug